# Generated by Django 5.1.6 on 2025-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecture'), ('admin', 'Administrator')], default='student', max_length=20),
        ),
    ]
