# Generated by Django 5.1.6 on 2025-03-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_lecture_number_user_college_user_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecture'), ('academic_registrar', 'Academic Registrar'), ('admin', 'Administrator')], max_length=20),
        ),
    ]
