# Generated by Django 5.1.6 on 2025-03-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Lecture_number',
            new_name='lecture_number',
        ),
    ]
